---
title: "Arbeidskrav 4(2)"
author: "Aleksander Josdal"
date: "4 11 2021"
output: html_document
bibliography: references.bib
---

### Spørsmål

Rapporten inneholder 5 studier som overordnet ser på effekten av treningsmotstand på muskelhypertrofi og styrke. Alle studiene har gjennomført en treningsintervensjon fra 8 - 12 uker. 2 studier tester effekten av forskjellig treningsmotstand på muskelhypertrofi og styrke, 1 studie ser på muskulære adaptasjoner til lav motstand med langsomme bevegelser, og de 2 siste ser mer på cellulære signalveier som aktiveres av hypertrofi-stimulerende styrketrening vs atrofi-stimulerende "de-training". Overordnet går dette som sagt under å teste treningsmotstand mot hypertrofi og styrke, det er dette jeg velger å sammenligne, selvom noen har også med utholdenhetsvariabler i datainnsamlingen [@schoenfeld2015]

### Alternative forklaringer

De fleste studiene formulerte ikke konkrete hypoteser som skulle testes, men mer problemstillinger som de skulle undersøke nærmere i lyset av en treningsintervensjon. Den ene som hadde en klar hypotese var Shoenfeld et al som gikk ut ifra at high-load er bedre for hypertrofi og styrke enn low-load.

### Logikk

Når det kommer til logikken mellom introduksjonen vs spørsmålet/hypotesen til studiene så handler de om å enten undersøke muskulære adaptasjoner til forskjellige treningsmetoder, eller undersøke signalveier i forbindelse med hypertrofi/artofi. Problemstillingene er basert på hva tidligere forskning har hevdet eller antyder. For eksempel at STARS-signalveien er involvert i hypertrofi i hjertemuskelceller, men det er usikkert hvordan denne fungerer i skjelettmuskulatur.

### Metode

+---------------------------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+-------------------+-------------+-------------+
|                                 | Shoenfelt et al                                                                    | Campos et al                                                                                             | Tanimoto og Ishii | Lamon et al | Léger et al |
+=================================+====================================================================================+==========================================================================================================+===================+=============+=============+
| Design                          | Tilfeldig fordeling i 2 grupper. En gruppe med 8-12 reps (HL), og en med 25-35     | Tilfeldig fordelt i 4 grupper: Low rep (3-5RM), Int rep (9-11RM), High rep (20-28RM), og kontrollgruppe. |                   |             |             |
|                                 | reps (LL). 3 økter i uken i 8 uker.                                                |                                                                                                          |                   |             |             |
|                                 |                                                                                    | 3 økter i uken i 8 uker.                                                                                 |                   |             |             |
+---------------------------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+-------------------+-------------+-------------+
| Utvalg                          | Veltrente menn. Gjennomsnittsverdier: 23.3 år, kroppsvekt 82.5kg, høyde på 175 cm. | Utrente men friske menn. Gjennomsnittsverdier: 22.5 år, kroppsvekt 77.8kg, høyde på 178.3 cm.            |                   |             |             |
+---------------------------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+-------------------+-------------+-------------+
| Rekruttering / utvalgsstørrelse | Rekruttert fra universitet.                                                        | Meldte seg frivillig.                                                                                    |                   |             |             |
|                                 |                                                                                    |                                                                                                          |                   |             |             |
|                                 | n = 24\                                                                            | n = 32,\                                                                                                 |                   |             |             |
|                                 | LL: n = 9\                                                                         | Low rep: n = 9\                                                                                          |                   |             |             |
|                                 | HL: n = 9                                                                          | Int rep: n = 11\                                                                                         |                   |             |             |
|                                 |                                                                                    | High rep: n = 7\                                                                                         |                   |             |             |
|                                 | Frafall: n = 6                                                                     | Kontroll: n = 5                                                                                          |                   |             |             |
+---------------------------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+-------------------+-------------+-------------+
| Gjennomføring av tester         | Ultralyd, tykkelse i                                                               | Analyse av kroppssammensetning, leg press, squat, and knee extension, først 1RM deretter max rep på      |                   |             |             |
|                                 | biceps, triceps og quadriceps. 1RM benkpress og squat. Pre og post tester.         | 60%. VO2 max og muskelbiopsi. Pre og post.                                                               |                   |             |             |
+---------------------------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+-------------------+-------------+-------------+
| Variabler til hypotesen         | Ultralyd, tykkelse i                                                               |                                                                                                          |                   |             |             |
|                                 | biceps, triceps og quadriceps. 1RM benkpress og squat                              |                                                                                                          |                   |             |             |
+---------------------------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+-------------------+-------------+-------------+
| Statistisk metode               | Deskriptiv                                                                         |                                                                                                          |                   |             |             |
|                                 | statistikk for å utforske distribusjonen. Paired t-test for å se forskjell         |                                                                                                          |                   |             |             |
|                                 | mellom pre og post. 2 sample t-test for å se prosentvis endring. Multiple          |                                                                                                          |                   |             |             |
|                                 | regression analysis med post verdier som avhengig variabel og baseline som         |                                                                                                          |                   |             |             |
|                                 | co-variat for å se forskjellen mellom gruppene.                                    |                                                                                                          |                   |             |             |
+---------------------------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+-------------------+-------------+-------------+
